run:
  skip-dirs:
    - test-cmds
  timeout: 5m
  tests: false # https://github.com/kolide/launcher/issues/1166

output:
  print-linter-name: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - paralleltest
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  disable:
    - deadcode
    - structcheck
    - varcheck

linters-settings:
  errcheck:
    ignore: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false
