run:
  skip-dirs:
    - test-cmds
  timeout: 5m

output:
  print-linter-name: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - paralleltest
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  disable:
    - deadcode
    - structcheck
    - varcheck
    #- paralleltest # https://github.com/kunwardeep/paralleltest/issues/8

linters-settings:
  errcheck:
    ignore: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false

issues:
  exclude-rules:
    - path: pkg/tpm/
      text: "Weird issues"
      linters:
        - goanalysis_metalinter
